name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        typst-version: ["0.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: imagemagick cargo
          version: 1.0

      - name: Install oxipng from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: oxipng

      - name: Install typst-test from github
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typst-test
          git: https://github.com/tingerrr/typst-test.git
          tag: ci-semi-stable

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version }}

      # - name: Compile tests
      #   run: |
      #     for f in ./tests/example\ copy\ {5..9}/test.typ; do typst compile "$f" && echo "compiled $f"; done

      - name: Run test suite
        run: typst-test run

      - name: Archive diffs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diffs
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
          retention-days: 5